# wider range of colors
set -s extended-keys on
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:Tc"
set -g mouse on

# start numbering at 1
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# ----- KEYBINDS ---------------------------
# Set C-Space to prefix
unbind C-b
set -g prefix C-Space
bind -n C-Space send-prefix

unbind r
bind r source-file ~/.tmux.conf

# New window keybind
unbind n
bind n new-window -c "#{pane_current_path}"

# Move between panes
unbind h
unbind j
unbind l
unbind k
bind h previous-window
bind C-h previous-window
bind j previous-window
bind C-j previous-window
bind l next-window
bind C-l next-window
bind k next-window
bind C-k next-window

# Rename tabs & sessions
unbind C-t
bind C-t command-prompt -I "rename-window '%%'"
unbind C-w
bind C-w command-prompt -I "rename-session '%%'"
unbind w
bind w choose-session

# Copy mode 
unbind c
bind c copy-mode
set -g mode-keys vi
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip.exe"

# Break panes to new windows and bring them back
unbind b
bind b break-pane
unbind m
unbind C-m
bind-key m choose-window -F "#{window_index}: #{window_name}" "join-pane -h -t %%"
bind-key C-m choose-window -F "#{window_index}: #{window_name}" "join-pane -v -t %%"

# Split panes
bind "'" split-window -v -c "#{pane_current_path}"
bind C-g split-window -h "#{pane_current_path}"


# ------------- PLUGINS -----------------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# ------- STYLE -----------------
set -g @dracula-show-powerline true
set -g @dracula-fixed-location "Shelton, CT"
set -g @dracula-plugins "weather "
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g @dracula-cpu-display-load true
set -g status-position top

set -g @dracula-colors "
# simple gruvbox Color Pallette
white='#ffffe0'         # tab bar fg
gray='#3e3e3e'          # tab bar bg
dark_gray='#ffffe0'     # session name fg
light_purple='#B16286'
dark_purple='#5a5a5a'   # active tab bg
cyan='#689D6A'
green='#484848'         # session name bg
orange='#484848'        # weather box bg
# orange='#4C3902'
red='#ff0000'
pink='#ff0'
yellow='#FAD556'        # prefix active session name bg
"

run '~/.tmux/plugins/tpm/tpm'


display "reloaded tmux config"
